import Head from 'next/head'
import Header from '../components/Header/Header'
import MenuMobile from '../components/MenuMobile/MenuMobile'
import Hero from '../components/Hero/Hero'
import { useState } from 'react'

export default function Home() {

  const [menuMobileIsOpen, setMenuMobileIsOpen] = useState(false)

  return (
    <div>
      <Head>
        <title>Ensinio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MenuMobile 
        menuMobileIsOpen={menuMobileIsOpen}
        setMenuMobileIsOpen={setMenuMobileIsOpen}
        />
        <Header setMenuMobileIsOpen={setMenuMobileIsOpen}/>
        <Hero />
      </main>
    </div> 
  )
}

export async function getStaticProps({locale}) {
  return {
    props: {
      messages: (await import(`../messages/${locale}.json`)).default
    }
  };
}

